CGN/trunk/src/main/java/de/jug/cologne/model/Player.java
package de.jug.cologne.model;

public class Player {

	public Player()
	{
		
	}
	
	public Player(String f, String n, String c)
	{
		id = counter;
		firstname =f;
		secondname = n;
		club = c;
		counter++;
	}
	
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getSecondname() {
		return secondname;
	}
	public void setSecondname(String secondname) {
		this.secondname = secondname;
	}
	public String getClub() {
		return club;
	}
	public void setClub(String club) {
		this.club = club;
	}
	public int getId() {
		return id;
	}
	
	private String firstname;
	private String secondname;
	private String club;
	
	private int id;
	
	private static int counter = 0;
}

CGN/trunk/src/main/java/de/jug/cologne/webbeans/model/CocktailSet.java
package de.jug.cologne.webbeans.model;

import java.util.HashSet;

import javax.enterprise.context.ConversationScoped;
import javax.enterprise.inject.Named;

@ConversationScoped
@Named
public class CocktailSet extends HashSet<String> {

  private static final long serialVersionUID = 3168113051521759428L;

  private boolean started;

  public boolean isStarted() {
    return started;
  }

  public void setStarted(boolean started) {
    this.started = started;
  }
}

CGN/trunk/src/main/java/de/jug/cologne/jsf/TestBean.java
package de.jug.cologne.jsf;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ActionEvent;
import java.io.Serializable;

@ManagedBean()
@SessionScoped
public class TestBean implements Serializable {
  private String value;

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public void goodBye(ActionEvent event) {
    value = "Good Bye!";
  }

  public void hello(ActionEvent event) {
    value = "Hello!";
  }
}

CGN/trunk/src/main/java/de/jug/cologne/webbeans/CocktailBean.java
package de.jug.cologne.webbeans;

import de.jug.cologne.webbeans.model.CocktailSet;

import java.io.Serializable;
import java.util.Arrays;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Current;
import javax.enterprise.inject.Named;

@RequestScoped
@Named("cocktailBean")
public class CocktailBean implements Serializable {

  private static final long serialVersionUID = -3501169454304213093L;

  private @Current Conversation conversation;

  private @Current CocktailSet cocktails;

  private String result;
  private String cocktail;

  public String startShopping() {
    conversation.begin();
    cocktails.setStarted(true);
    return null;
  }

  public String addCocktail() {
    cocktails.add(this.cocktail);
    return null;
  }

  public String endShopping() {
    cocktails.setStarted(false);
    conversation.end();
    setResult("PROST !!");
    return null;
  }

  public String[] getCocktails() {
    return cocktails.toArray(new String[cocktails.size()]);
  }

  public void setCocktail(String strs) {
    cocktails.addAll(Arrays.asList(strs));
  }

  public String getCocktail() {
    return null;
  }

  public void setResult(String res) {
    result = res;
  }

  public String getResult() {
    return result;
  }
  
  public boolean isInShopping() {
    return cocktails.isStarted();
  }

}

CGN/trunk/src/main/webapp/ajax.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="Ajax..."/>
    <ui:define name="content">
       <h:outputScript name="cgn.js" />
       <h:inputText value="#{sessionScope['cgnHack']}" id="tipper">
         <f:ajax event="keyup" render="output1" />
       </h:inputText>
       
       <p><h:outputText id="output1" value="#{sessionScope['cgnHack']}" /></p>
       
       <p><b>Ein weiteres Bsp</b></p>
       <h:commandLink value="Click me">
         <f:ajax onevent="callback" />
       </h:commandLink>
       
       
       <p>
         <h:commandButton value="...zum start"
           action="/start" />
       </p>    
       
    </ui:define>
</ui:composition>
    
    <p>
    </p>
</body>
</html>

CGN/trunk/src/main/webapp/cocktail.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>FOO</title>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="Apache Open Web Beans"/>
    <ui:define name="content">
        <h:commandButton value="Buy Cocktails"
                         actionListener="#{cocktailBean.startShopping}"/>
        <br/>
        <h:selectOneMenu id="list" rendered="#{cocktailBean.inShopping}" value="#{cocktailBean.cocktail}" >
            <f:selectItem itemLabel="Pick One" noSelectionOption="true" />
            <f:selectItem itemValue="Mai Tai" itemLabel="Mai Tai"/>
            <f:selectItem itemValue="Zombie" itemLabel="Zombie" />
            <f:selectItem itemValue="Touch Down" itemLabel="Touch Down" />
            <f:ajax event="click" execute="list" render="output" />
        </h:selectOneMenu>
        <br/>
        <h:dataTable rendered="#{cocktailBean.inShopping}" id="output" value="#{cocktailBean.cocktails}" var="cocktail">
          <h:column>
              <h:outputText value="#{cocktail}" />
          </h:column>
        </h:dataTable>


         <br/>
        <h:commandButton value="Pay"
                         actionListener="#{cocktailBean.endShopping}"/>
                         
        <p><h:outputText value="#{cocktailBean.result}" /></p>                 
        <h:messages/>
    </ui:define>
</ui:composition>

    <p>
    </p>
</body>
</html>

CGN/trunk/src/main/webapp/component.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:cgn="http://java.sun.com/jsf/composite/cgn"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="Eine Komponenten"/>
    <ui:define name="content">
      
      <cgn:slider maxRange="250" minRange="42"/>
    
    </ui:define>
</ui:composition>
    
    <p>
    </p>
</body>
</html>

CGN/trunk/src/main/webapp/js_ajax.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>FOO</title>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="Ajax, mit JavaScript API"/>
    <ui:define name="content">
        <h:outputText id="value" value="#{testBean.value}"/>
        <br/>
        <h:commandButton id="hello" value="Say Hello"
                         onclick="jsf.ajax.request(this, event, {execute: this.id, render: 'value'}); return false;"
                         actionListener="#{testBean.hello}"/>
        <br/>
        <h:commandButton id="goodBye" value="Say Good Bye"
                         onclick="jsf.ajax.request(this, event, {execute:'goodBye', render: 'value'}); return false;"
                         actionListener="#{testBean.goodBye}"/>
        <h:messages/>
    </ui:define>
</ui:composition>
    
    <p>
    </p>
</body>
</html>

CGN/trunk/src/main/webapp/start.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>FOO</title>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="Start"/>
    <ui:define name="content">
        <p><b>Hallo, JUG Cologne!</b></p>
        <h:graphicImage value="#{resource['images/princeduke2.jpg']}" />
    </ui:define>
</ui:composition>
    
    <p>
    </p>
</body>
</html>

CGN/trunk/src/main/webapp/vp1.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>FOO</title>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="View Params"/>
    <f:metadata>
      <f:viewParam id="id" name="playerId" />
    </f:metadata>
    <ui:define name="content">

    <p><b>Some football(->soccer) players:</b></p>

        <ul>
            <ui:repeat var="player" value="#{playersBean.players}">
                <li>
                    <h:link outcome="vp2">
                      <f:param name="playerId" value="#{player.id}"/>
                      #{player.secondname}
                    </h:link>
                </li>
            </ui:repeat>
        </ul>


    </ui:define>
</ui:composition>
    
    <p>
    </p>
</body>
</html>

CGN/trunk/src/main/webapp/vp2.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>FOO</title>
</head>
<body>
<ui:composition  template="/WEB-INF/templates/master.xhtml" >
    <ui:param name="title" value="View Params"/>
    <f:metadata>
      <f:viewParam id="id" name="playerId" value="#{playersBean.select}" />
      <f:event type="preRenderView" listener="#{playersBean.selectRightPlayer}"/>
   </f:metadata>
    <ui:define name="content">

    <p><b>Details:</b></p>

     Firstname: #{playersBean.selectedPlayer.firstname}<br/>
     Secondname: #{playersBean.selectedPlayer.secondname}<br/>
     Club: #{playersBean.selectedPlayer.club}<br/>


    <p><h:commandLink id="home" action="vp1.xhtml?faces-redirect=true"
        value="back..."/>
    </p>

    </ui:define>
</ui:composition>
    
    <p>
    </p>
</body>
</html>